### ISSUE TITLE
Fix further issues and race conditions with pav clean.

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#105]
Whatever function pav clean uses to list a bunch of tests needs to handle the fact that some of those tests will be broken and unloadable.

This can happen because of incompatible changes to Pavilion (which is typical), or more rarely because a test run is in the process of being created and run.

Update any function that loads a bunch of test objects to handle these cases, and return both a list of successfully loaded tests and information on failed loads (test id, error, timestamp of dir).

**Comment by francinelapid** [comment]
Sometimes, if I get an error the first time I run `pav clean`, it'll work fine the next time.

**Comment by Paul-Ferrell** [comment]
duplicates #69
