### ISSUE TITLE
pav slowness issues on large node count machines

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#11]
I'm seeing this in general, but it seems to be worst on Trinity. Both pav run and pav _run take a long time to get going, and I suspect it's caused by how long it takes to get scontrol data.  This needs to be profiled/timed to figure out where the actual bottleneck is.

**Comment by francinelapid** [comment]
`python3 -m cProfile -s cumtime pav.py run <test>` ?

**Comment by francinelapid** [comment]
[branch with cProfile](https://github.com/hpc/pavilion2/tree/python-profiling)

**Comment by Paul-Ferrell** [comment]
Added some optimizations and profiling that have taken care of this.
