### ISSUE TITLE
pav status --summary

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#111]
Add a 'summary' option to pav status. 

It should print a table of the counts of tests in each state:
```
State               | #  | %      | % Passed
----------------------------------------------------
COMPLETE    |  5 | 10%  | 80%
RUN_FAILED  |  1 | 2%    | N/A
```

Make it as pretty as you can. An overall progress bar (in color), for instance, would be nice.

**Comment by Paul-Ferrell** [comment]
You might also have separate rows for tests that 'pass' or 'fail'.

**Comment by Paul-Ferrell** [comment]
None of my rough examples are requirements, just design something you're proud of.

**Comment by Paul-Ferrell** [comment]
Checkout how I output status info for the builds in the new release. (You don't need anything that complicated in terms of handling threads).

**Comment by nicholas-sly** [comment]
While we're at it, I'd like to request another feature for the `pav status` command.  A method to only show the tests that have a certain state or result would be very helpful.  Consider the following:

```
-bash-4.2$ pav status | grep 'FAIL'
      |                                       |          |          | FAIL
```

That's not terribly helpful.  Apparently one test failed, but I'm not sure what happened to the rest of the text.  A `-r`/`--results` option for specifying the results you want to see would be nice.  Similarly, I could see a `-s`/`--state` option for specifying a given state you want to see being helpful as well.

**Comment by CalvinDSeamons** [comment]
Yeah I agree, while I was making the general summary I thought that would be useful. 
I though `pav status --list FAIL` made the most sense but `--state` would also work.
