### ISSUE TITLE
pytz not in sub_repos

### ISSUE THREAD

**Issue by BenCasses** [hpc/pavilion2#119]
following instructions from https://pavilion2.readthedocs.io/en/latest/ in pavilion version 2.1 pytz is not cloned by submodule update and thus is not available for make build

**Comment by j-ogas** [comment]
@BenCasses The prerequisite section of the documentation appears to be out of date. `pytz` was initially required but has since been removed.

**Comment by j-ogas** [comment]
Closing, resolved with #143.
