### ISSUE TITLE
Make sure the test full name is the test.name value, and that's used everywhere.

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#15]
Especially in pav status. The name should include the suite, test, and sub_name (if set).

**Comment by francinelapid** [comment]
suite.test."subname"???

**Comment by francinelapid** [comment]
subname should default to the value of permuted variable
default behavior should look like:
```
permutes_on: [compiler, mpi]
subname: "{{compiler}}_{{mpi}}" 
```

**Comment by Paul-Ferrell** [comment]
This was a bug I found. It'll be fixed when I merge my current work.
