### ISSUE TITLE
There are two permutations sections in the readthedocs documentation

### ISSUE THREAD

**Issue by francinelapid** [hpc/pavilion2#161]
https://pavilion2.readthedocs.io/en/latest/tests/variables.html#permutations

https://pavilion2.readthedocs.io/en/latest/advanced.html#permutations

I think there should only be one

**Comment by Paul-Ferrell** [comment]
One is in the 'usage' documentation, and is meant to quickly say 'hey look, this feature exists!'
The other is in the 'feature' documentation, and is meant to fully document the feature.

**Comment by Paul-Ferrell** [comment]
I added this for discussion at our next meeting.

**Comment by Paul-Ferrell** [comment]
- Add link to 'feature' documentation at the top of each usage section. 
- Add bit about doing this to documentation documentation.

**Comment by Paul-Ferrell** [comment]
Dealt with.
