### ISSUE TITLE
generic way to access slurm (WLM) environment variables?

### ISSUE THREAD

**Issue by j-ogas** [hpc/pavilion2#164]
Could a test.yaml file have a generic way to reference common WLM environment variables. For example, in some scripts we use things like, `$SLURM_JOBID`, could this be replaced with a pav2 generic variable? Like `PAV.JOBID` etc.

**Comment by Paul-Ferrell** [comment]
This is what scheduler variables are for. If you would like that to be in a scheduler variable, that can be done easily.
