### ISSUE TITLE
pav run count (repeat) option

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#165]
Add an option to have pav run create 'N' instances of the given tests. 

```
pav run --repeat 5 supermagic imb.imb
```
Would run both the supermagic and imb tests 5 times.

**Comment by CalvinDSeamons** [comment]
Kody hungers for tickets... he stole this from me while I was in my stricken state of delirium last Thursday.  Expect a PR from him, I'm just going to add him as a assignee as well.
