### ISSUE TITLE
Add a pre-commands section to both run and build

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#19]
Some machines need certain commands run to set up their module environment depending on your shell. This would be the place to do that (in a host config file), among other useful things.

**Comment by francinelapid** [comment]
Is this the same as the `preamble` config element (for the build and run sections)?

Or would these pre-commands need to be run before and outside the `build.sh` and `run.sh`?

**Comment by Paul-Ferrell** [comment]
Yes! I needed it for these tests, and forgot I had a ticket for it.


________________________________
