### ISSUE TITLE
Absolute to relative symlinks fail to be relative to the location of the symlink

### ISSUE THREAD

**Issue by nicholas-sly** [hpc/pavilion2#237]
When creating the relative symlinks in order to enable moving the build directory from the tmp location to the final placement, the relative symlink seems to be relative to the build directory and not to the location of the symlink (e.g. if in a subdirectory, it fails to point to the parent directory, which is the build directory, before pointing to the final location).  

A unit test should be created with the symlink in a subdirectory.  The file to which it points can be in the base build directory or even the same subdirectory.

**Comment by Paul-Ferrell** [comment]
Hah, the moment you said that, I realized I done fucked up. I'll fix it first thing Tuesday.


________________________________
