### ISSUE TITLE
Allow for non-relocatable builds

### ISSUE THREAD

**Issue by nicholas-sly** [hpc/pavilion2#250]
Provide an option that allows the test to be built in the final location rather than in a temporary directory for tests that aren't amenable to relocation.  A new config option under the build section of `relocatable: true` that is `true` by default and allows for `false` would allow for the specification.  

A possible alternative would be to create the final directory before starting the build and allow it to be referenced using a variable so builds that allow you to specify a prefix can use that.  

Either way, unless LAP has some special mechanism to allow the builds to be relocatable that I haven't found yet (already sent an email inquiring about this), this will enable building and running LAP/FLAG under Pavilion.

**Comment by Paul-Ferrell** [comment]
This was fixed in another merge request recently.
