### ISSUE TITLE
Expand environment variables in pavilion.yaml config paths.

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#255]
Some users need these paths to be more dynamic. 

 - Add support for expanding environment variables to all paths specified in the pavilion.yaml.
 - Add documentation denoting that this is done (both in docs/ and in the config description).

**Comment by paulbry** [comment]
I took a little bit of time today and tried to implement the changes to the `lib/pavilion/config.py` - https://gist.github.com/paulbry/4e03107148b71a1ab80b435980f1f247

It's a bit messy with the use of `str()` and `Path()` but noticed in the docs `envparser()` didn't accept path object until 3.6. 

The one issue I ran into was how to organize unit tests for the change. I was thinking it would be a configuration defined somewhere under `test/data/???`. Then have some sort of test that could assert the desired directory paths are realized. Though I wasn't sure where to include such tests in the `lib/pavilion/unittest.py` application.

If it's something that would make sense to finish up and put in as an MR I would be glad to. If you had a better idea on how to do this that's also great. The exercise gave me a chance to look a little closer at the tool.

**Comment by Paul-Ferrell** [comment]
@paulbry - Hadn't noticed you did that until just now. About an hour after you posted this I put up a pull request to fix this issue. https://github.com/hpc/pavilion2/pull/257

I fixed by making a custom yaml_config ExPathElem class that handles the environment resolution, and just switched all the config items that want a path to that. I test the new ExPathElem class itself; if it works as expected on its own, the whole thing should work too.
