### ISSUE TITLE
Pavilion tests inherit environment of the shell invoking pav

### ISSUE THREAD

**Issue by jennfshr** [hpc/pavilion2#264]
I'd like pavilion to create a pristine login shell under which pavilion runs, whether in raw or under a scheduler.  Blindly inheriting the shell environment under which pav is invoked could either obfuscate problems, or create them.

**Comment by Paul-Ferrell** [comment]
There is no automated way we can do this:
  - Pavilion needs some sort of environment. 
    - On login, that comes from bash running /etc/profile, which in turn typically runs ~/.bashrc or ~/.bash_profile
    - There's no way to undo running a user's bash profile stuff, without getting rid of everything.
  - This means we would need to know everything about what should be in the environment and what shouldn't be. 
    - The only solution to this is to have a system specific script provided by the user that initializes an environment for Pavilion.
  - This would be fragile though, as system changes would break it. 
  - But wait, we already have such a script on every system. It's the `/etc/profile` script. Any fragility is offset by the fact that it has to work for the system to work. It happens to run a user's ~/.bashrc, but maybe people shouldn't do to much custom crap to their environments if they're going to use that environment to run tests?

**Comment by Paul-Ferrell** [comment]
The best solution for this is to use a dedicated user (hpctest) for testing.
