### ISSUE TITLE
Remove requirement for a `source_path` value when `source_url` is provided and `source_download` is set to latest

### ISSUE THREAD

**Issue by nicholas-sly** [hpc/pavilion2#274]
Allow for a default `source_path` value to be generated when a `source_url` is provided and `source_download` is set to `latest`.  The `source_path` can be based on the test name.  In the case of inheritance, the top-level test that is inherited from by others will set the `source_path` name and everything else will inherit this value until it is overridden by a specified value.  In the case of permutations, this only becomes an issue if a variable that is being permuted on is used in the `source_url`, so the variable value should be used in conjunction with the test name to determine the `source_path` value.

**Comment by Paul-Ferrell** [comment]
I think the solution to this is to hash the url itself, and make that the file name.

**Comment by Paul-Ferrell** [comment]
I implemented this in 2.2
