### ISSUE TITLE
Mac compatibility issues

### ISSUE THREAD

**Issue by PREtrent** [hpc/pavilion2#279]
These are all on MacOS 10.14.6:

1. Line 5 of `bin/pav`: the `realpath` command is a part of the GNU coreutils package, which isn’t installed on Mac by default. This prevents the user from starting pav at all. Running `brew install coreutils` will install the correct package; this should be added to the install documentation.

2. Line 17 of `lib/pavilion/plugins/sys_vars/sys_arch.py`: `uname -i` isn’t a valid command on Mac, which prevents running `pav show tests`. The Mac equivalent of this is `uname -m`.

3. After fixing these two issues, `pav run` still fails due to the Mac not having a `/proc/meminfo` file. I can't find a great alternative to this; `sysctl -a` is kiiind of similar.

I'm not sure if these are actually issues or if I'm just dumb and not setting up my hosts files correctly (this is Kody's theory), but this setup process seems much more seamless on the clusters, and after a couple hours of searching I can't find anything in the documentation about where to specify "I'm on a Mac, please do Mac things."

**Comment by Paul-Ferrell** [comment]
Pavilion isn't compatible with Mac, and was never meant to be.
