### ISSUE TITLE
Pav clean needs to delete build.finished files.

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#299]
Also, a build with a .finished file but no directory should auto-delete that file too.

**Comment by kjeverson** [comment]
This has been added in the refactor clean PR #297

**Comment by kjeverson** [comment]
Just saw this is for pav cancel...will work on it now

**Comment by kjeverson** [comment]
Quick patch was implemented and pushed to the 2.2.1 branch, the more elegant solution exists in the refactored clean command PR #297
