### ISSUE TITLE
Assistance in creating PBS scheduler plugin.

### ISSUE THREAD

**Issue by coneheadusa** [hpc/pavilion2#313]
I am planning to use Pavilion2 on a project for NOAA and would like to create a plugin for the PBS scheduler. The documentation for writing a scheduler plugin states: 
 "This page is unfortunately under construction. If you’re interested in writing your own scheduler plugins, let us know and we’ll make fixing this a top priority."   This is my way of letting you know. 

Thank you,
Randy Smith  (Former LANL HPC employee)

**Comment by Paul-Ferrell** [comment]
It's a great way to do it. I'll get on that first thing in the morning.

**Comment by coneheadusa** [comment]
Any idea when this information will be available?

**Comment by coneheadusa** [comment]
Thank you for the update. I’ll share the resulting plugin when I’ve finished.

**Comment by Paul-Ferrell** [comment]
I've created a merge request for this. It should be merged into master by the end of the day, which will also put it up on readthedocs.
