### ISSUE TITLE
More informative results tables for permutations

### ISSUE THREAD

**Issue by nicholas-sly** [hpc/pavilion2#32]
When the status and/or results of a list of tests are being displayed, they should have a column specifying what the values of variables over which the test is permuting.  As an example:

 Name                       | Id   | Result
----------------------------|------|--------
 license-check.open-fe      | 1028 | PASS
 license-check.open-fe      | 1029 | FAIL

This doesn't tell me which one failed.  It could be added to the results section as a constant, but that doesn't help in the case of a status.  A formatted print of the json structure:

 Name                       | Id   | Permutations | Result
----------------------------|------|--------|---
 license-check.open-fe      | 1028 | license-daemons: | PASS
 | | | { name: Intel |
 | | | port: 51010 } |
 license-check.open-fe      | 1029 | license-daemons: | FAIL
 | | | { name: Intel |
 | | | port: 51110 } |

Also:

 Name                       | Id   | Permutations | Result
----------------------------|------|--------|---
hello_mpi.toss             | 1046 | compiler: gcc | FAIL
| | | mpis: openmpi |
 hello_mpi.toss             | 1047 | compiler: gcc | PASS
| | | mpis: mvapich2 |

**Comment by j-ogas** [comment]
This should definitely be implemented one way or another.

**Comment by francinelapid** [comment]
#22 changes `pav results -f` such that the output shows the entire `run.log` from that test. If you specify which permuted variable you want to see using the constant result parser, then you will be able to see which values were used when you run `pav results -f`.

Right now it doesn't print the results as a table anymore and it can only print 1 test (#12).

**Comment by Paul-Ferrell** [comment]
Duplicates #15
