### ISSUE TITLE
Failed job causes error in parsing results.

### ISSUE THREAD

**Issue by coneheadusa** [hpc/pavilion2#343]
The job under test crashed resulting in an output file with no usable information.

"error while loading shared libraries: libimf.so: cannot open shared object file: No such file or directory"

PAV reported this:
Unexpected error parsing results: Invalid value 'None' given to num.. (This is a bug, you should report it.)

Output from kickoff log is attached.
[kickoff268.txt](https://github.com/hpc/pavilion2/files/5505163/kickoff268.txt)

**Comment by nicholas-sly** [comment]
This is not entirely unexpected.  As you can see in the [tutorial](https://pavilion2.readthedocs.io/en/latest/tutorials/writing_a_test.html#run-scripts), one option is to add "`|| exit 1`" to a command to ensure that the run script will exit with the appropriate exit code to tell Pavilion that it has failed.  If the final command in your run script returns a zero value exit code regardless of whether your test ran appropriately, Pavilion will assume that everything went well and proceed to the result parsing and evaluation.  Unfortunately, this is a result of having the test bash scripts run independently of the test framework.  We use this method in our own tests.  Let us know if the documentation doesn't convey this very well and we'll see if we can improve it.

**Comment by coneheadusa** [comment]
Thank you for the prompt reply; the documentation is quite clear.    I am impressed with the power and flexibility pavilion 2 has to offer.
