### ISSUE TITLE
Slurm plugin include_nodes regex doesn't support comma-separated lists

### ISSUE THREAD

**Issue by nicholas-sly** [hpc/pavilion2#351]
Regex ostensibly supports all formats accepted by `srun -w <node_list>`, but doesn't support lists like `fw0[01,11,21,42]` whereas srun does.  When trying to use what nodes are available on a machine that are disparate, supporting this capability is very useful.

**Comment by kjeverson** [comment]
Works in master:
```
Original: fw0[01,11,21,42]
List matches regex
Parsed: ['fw001', 'fw019', 'fw028', 'fw042']
```
