### ISSUE TITLE
Wait command not identifying tests when used inconjunction with a series

### ISSUE THREAD

**Issue by paulbry** [hpc/pavilion2#379]
First, I'm excited about the addition of series it'll prove really helpful.

I've run into issue with the following command: `pav series test-auth && pav wait`. Previously I would run something similar with a traditional test files (e.g., `pav run auth && pav wait`). This would work as expected, waiting until all tests associated with `auth.yaml` to finish. With series this is no longer the case.

Out of curiously I simply added a print statement to the `plugins/commands/wait.py`:

```python
def run(self, pav_cfg, args):
      """Wait for the requested tests to complete."""
      ...
      tests = status_utils.get_tests(pav_cfg, args.tests, self.errfile)
      print(tests)
```

Re-running the original command I can see there are not tests identified at this time:

```
$ pav series test-auth && pav wait
Started series s3.
Run `pav status s3` to view status.
PGID is 257.
To kill, use `pav cancel s3`.
[]
```

Adding a sleep command appears to correct this:

```
$ pav series test-auth && sleep 1 && pav wait
Started series s4.
Run `pav status s4` to view status.
PGID is 354.
To kill, use `pav cancel s4`.
[4]
```

Note, I'm running with the tagged 2.3 release and in the example example, used in the code snippets, there is only a single test.

**Comment by Paul-Ferrell** [comment]
We're currently working on a 2.3.1 release, we'll add this to that.
