### ISSUE TITLE
Relative timestamp format

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#42]
Write a function (in the utils.py library) that takes a timezone aware datetime object and produces a time string with information relative to the current time.

Only include each of the following if they differ from a regular timestamp. 
  - timezone (based on the UTC offset, not the timezone name). 
  - year
  - day/month

The easiest way to do this is to dynamically build the datetime.strftime format string.

**Comment by Paul-Ferrell** [comment]
Oh, and use this new format in all command printouts. You can do this through the draw_table options (ask Paul).

**Comment by j-ogas** [comment]
TODO: 
- [ ] Remove all timezone stuff.

**Comment by j-ogas** [comment]
Closing via #49.
