### ISSUE TITLE
Method TestAttributes.load_legacy_attributes failure

### ISSUE THREAD

**Issue by dmageeLANL** [hpc/pavilion2#431]
If a database is being recreated.  And someone who is no longer a user on our systems owns directories in `$PAV_CONFIG_DIR/working_dir/test_runs` (Kody).  Then rebuilding test_run_attr_transform.db through index will fail because the user key of the attrs dict which is set to: self.path.owner() will fail.  Because there's a uid but the system doesn't know who it is.

**Comment by Paul-Ferrell** [comment]
ooh, fun.
