### ISSUE TITLE
Add `pav status history <jobid>`

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#45]
Show the full status history of the given job.

**Comment by Paul-Ferrell** [comment]
Maybe in a table.

**Comment by francinelapid** [comment]
`pav status` takes in a positional argument `tests` (in which it can take 0, 1, or multiple test ids).

I think adding a `history` should be implemented as an optional argument. So something like 
`pav status <test id> --history/-h`

Also, should the command raise an exception if the user inputs multiple test ids or any series ids while trying to use the `--history` flag?
