### ISSUE TITLE
pav graph does not write png file.

### ISSUE THREAD

**Issue by coneheadusa** [hpc/pavilion2#513]
Under pav version 2.4,  if I use the command below, no output is generated that I can find and no errors are thrown either. Please advise.

pav graph user.42 user.40 user.38 user.36  '-x per_file.*.mean_tflops' '-y keys(per_file)' --outfile dgemm.png
Generating Graph...
Completed. Graph saved as 'dgemm.png'

**Comment by Paul-Ferrell** [comment]
I fixed it in master.

**Comment by coneheadusa** [comment]
Thank you!

**Comment by Paul-Ferrell** [comment]
I'll check that out this morning. Thanks for the heads up.


________________________________
From: Randy Smith ***@***.***>
Sent: Friday, June 24, 2022 8:33 AM
To: hpc/pavilion2
Cc: Subscribed
Subject: [EXTERNAL] [hpc/pavilion2] pav graph does not write png file. (Issue #513)


Under pav version 2.4, if I use the command below, no output is generated that I can find and no errors are thrown either. Please advise.

pav graph user.42 user.40 user.38 user.36 '-x per_file.*.mean_tflops' '-y keys(per_file)' --outfile dgemm.png
Generating Graph...
Completed. Graph saved as 'dgemm.png'
