### ISSUE TITLE
yaml_config?

### ISSUE THREAD

**Issue by vsoch** [hpc/pavilion2#538]
Hi! I'm not sure if I'm missing something, but it says that yaml_config is required, but I don't see it in requirments.txt and the linked repository is 404 https://github.com/lanl/yaml_config. Is this the right repository for the Pavilion testing framework? I'm looking to develop for it and add a new scheduler / executor. Thanks!

**Comment by vsoch** [comment]
This seems to be the library from: https://github.com/lanl-preteam/yaml_config. However the install deps script is forcing the user to create a venv, and then it's creating a bunch of dead symbolic links to its own lib directory. I'm confused because either we can use pip (and install to our preference of Python) or there is an approach like spack takes (and we do not use pip). When I write my own install routine to be able to use my preferred python, I hit #539. Thanks!

**Comment by Paul-Ferrell** [comment]
The symlinks in lib always exist whether you run `bin/setup_pav_deps` or not, and regardless of what mode you run it in. They won't hurt anything if they're dead.  I should drop a README in there that explains that.

Running the `bin/setup_pav_deps` script should also pull down the correct yaml_config module, and install it appropriatly. 

Alternatively, if you clone the Pavilion repo with git and run `bin/setup_pav_deps`, it will just get all those dependencies as git submodules.

**Comment by vsoch** [comment]
Thanks @Paul-Ferrell ! I did eventually figure it out but I ran into #539. Also, the links in the doc to yaml_config are broken so it might help to fix that.

For install, I think it would be good to either:

1. Don't use pip and install things locally and manually, or
2. Allow using pip

It's kind of confusing (and comes out at least looking like it's broken) to simultaneously take both approaches.

**Comment by vsoch** [comment]
Awesome thank you!

**Comment by Paul-Ferrell** [comment]
I've been told you guys are working on setting up a Flux scheduler plugin for Pavilion. Scheduler plugins are a bit complicated - let me know if you want a run-down of how they work or any other sort of help.  I'm on the Spack Slack and on DOE Mattermost.

**Comment by vsoch** [comment]
Sure thing! I indeed am doing exactly that - I will ping you if/when I run into trouble! I figure if i hit bugs I should report them here because others might too.

**Comment by Paul-Ferrell** [comment]
Made a separate ticket for moving in yaml_config. #543
