### ISSUE TITLE
pav series run not working for v2.4   

### ISSUE THREAD

**Issue by coneheadusa** [hpc/pavilion2#580]
Using a copy of the sanity_tests.yaml from the Pavilion2 documentation,  I get this message when I do "pav series run sanity_tests":
Unknown error running command series. Invalid config key 'series' given under SeriesConfigLoader called '<root>'
I get the same error when I try to run any of my previously working series yaml files.   Please advise.

**Comment by coneheadusa** [comment]
Hi, Paul.  Any update on this?   I have a large project starting soon that will give Pavilion2 more visibility in the HPC community and I would like to use "pav series run"  as part of that configuratio.   However, no mater how I configure  series_test.yaml file, I get " Invalid config key 'series' given under SeriesConfigLoader called '<root>'."  Do you have any suggestions.    I've reduced the test.yaml file down to one line "series:"  and I still get the Invalid config key 'series' messages.  Thanks, Randy Smith

**Comment by Paul-Ferrell** [comment]
Try the `series.back-compat-warn` branch. It should warn you what's gone wrong (the `series` key in series files changed to `test_sets`).

If that works for you, I'll go ahead and merge this into master.

**Comment by coneheadusa** [comment]
Thank you very much.  The series.back-compat-warn branch works great.
