### ISSUE TITLE
Add a 'version' section for test configs

### ISSUE THREAD

**Issue by nicholas-sly** [hpc/pavilion2#65]
Add a version key to the base subtest config format.  Have this also included as a default result key.  The default value can be something like '0.1' or '1.0'.

**Comment by Paul-Ferrell** [comment]
Three version actually
 - Test version (arbitrary, save in results)
 - Min Pavilion Version
 - Current Pavilion version saved in results

**Comment by Paul-Ferrell** [comment]
- Make the pavilion version a pavilion variable.

**Comment by Paul-Ferrell** [comment]
- Min Pav Version should be a range.
