### ISSUE TITLE
Make 0 padding of node names in slurm plugin optional

### ISSUE THREAD

**Issue by nicholas-sly** [hpc/pavilion2#688]
Some machines have 0-padding in their node names (e.g. - nid01000) whereas some do not (machine1, machine10, etc).  The slurm plugin currently always adds the 0 padding, which breaks when trying to submit a job to a specific node list when it is specifying nodes that don't exist (e.g. - machine01).  Making this optional allows for specifying at the host level which option to use, as it may differ between different machines at the same site.

**Comment by Paul-Ferrell** [comment]
I just fixed this in PR #685
