### ISSUE TITLE
Pavilion checks for node availability during build only run

### ISSUE THREAD

**Issue by tygoetsch** [hpc/pavilion2#712]
I noticed when I was attempting to build imb that pavilion checked for node availability and failed to build even though it doesn't need to make this check for a build only run. Example and git commit hashes below:

```
tgoetsch@ro-rfe1:/usr/projects/hpctest/tgoetsch/repos/pav2-lanl-> pav build imb
Created Test Series cmdline.
Resolving Test Configs: 100%
Error making tests for series 's6'.
  Error creating test 'imb.base' in test set 'imb'
    Errors were found when creating test imb.base.0.
    Insufficient nodes. Asked for 342-342 nodes, but only 318 were left after filtering.
...
```

When I added the `-c schedule.nodes=16` cmdline arg the error goes away.

```
tgoetsch@ro-rfe1:/usr/projects/hpctest/tgoetsch/repos/pav2-lanl-> pav build imb -c schedule.nodes=16
Created Test Series cmdline.
Resolving Test Configs: 100%
Creating Test Runs: 100%
Test set 'imb' created 1 tests, skipped 1, 0 errors.
To see why each test was skipped, run:
  `pav series states --skipped`
Building 1 tests for test set imb.
BUILD_SUCCESS: 1
```

pav2-lanl hash: fbee05fc252ee1d422b1b3a54c56237b7ae96f3b (origin/develop head)
pavilion2 hash: f502ca86fa27f4bc894aa19232c9f1f42361e269 (origin/master head)

**Comment by dmageeLANL** [comment]
Good point. I'll check it out.

**Comment by dmageeLANL** [comment]
I'd like to have this flag set automatically when none of the tests have 'on_nodes' set. But there is a command line flag to bypass it. Just: `pav build -l imb`.

**Comment by dmageeLANL** [comment]
Well, that doesn't exactly work actually, the same mechanism is still in play. New commit fixes it by overwriting any override or internal calculation of the number of nodes if build_only is set.
