### ISSUE TITLE
run_result being accessed before assignment.

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#781]
We seem to be hitting an issue with result parsing in Pavilion.  Seems like it's trying access run_result before assignment.  Oddly, it's only happening on some tests.  Maybe when the test application has completed output, but not returned a value and the pavilion timeout is hit.  Results in a results.json with only 5 values in it.  The results.log is empty.  Running pav results -L -r <test_id> results in a full log that shows a full test result before adding result parsed entries, it parses the table as instructed, but then fails with the run_result issue and ends up with a very sparse results.json saved to disk.

**Comment by hwikle-lanl** [comment]
Can you provide me with one of the tests that's giving this behavior?

**Comment by hwikle-lanl** [comment]
Waiting on Nick to provide failing test.
